In [2]:
l= list(range(10))
type(l[0])

int

In [3]:
l2= [str(c) for c in l]
l2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [12]:
for x in range (1,11):
    print(f"table of number {x}")
    print("------------------")
    for i in range(1,11):
        print(f"{x}*{i}={x*i}")

table of number 1
------------------
1*1=1
1*2=2
1*3=3
1*4=4
1*5=5
1*6=6
1*7=7
1*8=8
1*9=9
1*10=10
table of number 2
------------------
2*1=2
2*2=4
2*3=6
2*4=8
2*5=10
2*6=12
2*7=14
2*8=16
2*9=18
2*10=20
table of number 3
------------------
3*1=3
3*2=6
3*3=9
3*4=12
3*5=15
3*6=18
3*7=21
3*8=24
3*9=27
3*10=30
table of number 4
------------------
4*1=4
4*2=8
4*3=12
4*4=16
4*5=20
4*6=24
4*7=28
4*8=32
4*9=36
4*10=40
table of number 5
------------------
5*1=5
5*2=10
5*3=15
5*4=20
5*5=25
5*6=30
5*7=35
5*8=40
5*9=45
5*10=50
table of number 6
------------------
6*1=6
6*2=12
6*3=18
6*4=24
6*5=30
6*6=36
6*7=42
6*8=48
6*9=54
6*10=60
table of number 7
------------------
7*1=7
7*2=14
7*3=21
7*4=28
7*5=35
7*6=42
7*7=49
7*8=56
7*9=63
7*10=70
table of number 8
------------------
8*1=8
8*2=16
8*3=24
8*4=32
8*5=40
8*6=48
8*7=56
8*8=64
8*9=72
8*10=80
table of number 9
------------------
9*1=9
9*2=18
9*3=27
9*4=36
9*5=45
9*6=54
9*7=63
9*8=72
9*9=81
9*10=90
table of number 10
------------------
10*1=10
10*2=

In [17]:
import numpy as np
x= np.random.randint(5, size=(3,3))
y= np.random.randint(7, size=(3,3))

In [20]:
ans = np.random.randint(1,size=(3,3))
ans

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
l=len(y[0])
for i in range(len(x)):
    for j in range(l):
        for k in range(len(y)):
            ans[i][j] += x[i][k] * y[k][j]
  
print (ans)

[[22 26 18]
 [11 16  9]
 [15 18  9]]


In [1]:
from datetime import date, timedelta
now = date.today()
num= int(input("Enter the no. of days to add: "))
print("Current date: "+ str(now))
td=now + timedelta(num)
print("Changed date and time on Addition: "+str(td))
num_sub= int(input("Enter the no. of days to subtract: "))
td=now - timedelta(num_sub)
print("Changed date and time on Subtraction: "+str(td))

Enter the no. of days to add: 5
Current date: 2021-09-07
Changed date and time on Addition: 2021-09-12
Enter the no. of days to subtract: 5
Changed date and time on Subtraction: 2021-09-02


In [4]:
import math

radius=int(input("Enter the radius of circle: "))
length=int(input("Enter the length of rectangle: "))
breadth=int(input("Enter the breadth of rectangle: "))
area_circle=math.pi*radius*radius
perimeter_c=2*math.pi*radius
area_r=length*breadth
perimeter_r=2*(length+breadth)
print("Area of circle: "+str(area_circle))
print("Perimeter of circle: "+str(perimeter_c))

print("Area of rectangle: "+str(area_r))
print("Perimeter of Rectangle: "+str(perimeter_r))

Enter the radius of circle: 3
Enter the length of rectangle: 8
Enter the breadth of rectangle: 9
Area of circle: 28.274333882308138
Perimeter of circle: 18.84955592153876
Area of rectangle: 72
Perimeter of Rectangle: 34


In [6]:
print("The equation is of form ax2+bx+c")
import cmath
a=float(input("Enter a:"))
b=float(input("Enter b:"))
c=float(input("Enter c:"))
d=(b**2)-(4*a*c)
r1=(-b-cmath.sqrt(d))/(2*a)
r2=(-b+cmath.sqrt(d))/(2*a)
print("The roots are: "+str(r1)+" and "+str(r2))

The equation is of form ax2+bx+c
Enter a:4
Enter b:5
Enter c:6
The roots are: (-0.625-1.0532687216470449j) and (-0.625+1.0532687216470449j)
