In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from scipy.stats import chi2_contingency as cc
from scipy.stats import chi2

df=[[69,120,123],
    [56, 80, 52]]

st,p,dof,exp = cc(df)

print('dof=%d' %dof)
print(exp)

prob = 0.95

cr= chi2.ppf(prob,dof)

print('probab=%.3f , critical =%.3f, stat=%.3f' %(prob,cr,st))

if st>= cr:
    print('rejected H0')
else:
    print('failed to reject H0')
    
al=0.05
print('sig=%.3f, p =%.3f' %(al,p))

if p <= al:
    print('rejected H0')
else:
    print('failed to reject H0')
    

dof=2
[[ 78.  124.8 109.2]
 [ 47.   75.2  65.8]]
probab=0.950 , critical =5.991, stat=7.891
rejected H0
sig=0.050, p =0.019
rejected H0


In [3]:
df = pd.read_csv("vgsales.csv")
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [4]:
df2 = pd.crosstab(df['Genre'] , df['Publisher'])
df2

Publisher     10TACLE Studios  1C Company  20th Century Fox Video Games  \
Genre                                                                     
Action                      0           0                             4   
Adventure                   1           0                             0   
Fighting                    0           0                             0   
Misc                        0           0                             0   
Platform                    0           0                             0   
Puzzle                      1           0                             0   
Racing                      0           1                             0   
Role-Playing                0           1                             0   
Shooter                     0           0                             1   
Simulation                  0           0                             0   
Sports                      0           0                             0   
Strategy                    1           1                             0   

Publisher     2D Boy  3DO  49Games  505 Games  5pb  7G//AMES  989 Sports  ...  \
Genre                                                                     ...   
Action             0   17        0         21    5         0           0  ...   
Adventure          0    3        0          7   49         0           0  ...   
Fighting           0    1        0         11    1         0           0  ...   
Misc               0    0        0         31    0         1           0  ...   
Platform           0    1        0          6    0         0           0  ...   
Puzzle             1    1        0         15    0         1           0  ...   
Racing             0    0        0          2    0         0           0  ...   
Role-Playing       0    1        0         10    1         0           0  ...   
Shooter            0    5        0         18    3         0           0  ...   
Simulation         0    0        0         41    2         2           0  ...   
Sports             0    6        1         27    0         0           1  ...   
Strategy           0    1        0          3    0         0           0  ...   

Publisher     Zushi Games  bitComposer Games  dramatic create  fonfun  iWin  \
Genre                                                                         
Action                  1                  0                1       0     0   
Adventure               1                  0                4       0     0   
Fighting                0                  0                0       0     0   
Misc                    1                  0                0       0     0   
Platform                0                  0                0       0     0   
Puzzle                  2                  0                0       0     1   
Racing                  3                  1                0       0     0   
Role-Playing            1                  0                0       0     0   
Shooter                 2                  0                0       0     0   
Simulation              2                  4                0       1     0   
Sports                  3                  0                0       0     0   
Strategy                2                  0                0       0     0   

Publisher     id Software  imageepoch Inc.  inXile Entertainment  mixi, Inc  \
Genre                                                                         
Action                  0                0                     0          1   
Adventure               0                1                     0          0   
Fighting                0                0                     0          0   
Misc                    0                0                     0          0   
Platform                0                0                     0          0   
Puzzle                  0                0                     0          0   
Racing                  0                0                     0          0

In [6]:
val = cc(df2)
val

(25587.348135120996,
 0.0,
 6347,
 array([[0.60018138, 0.60018138, 1.0003023 , ..., 0.20006046, 0.20006046,
         0.40012092],
        [0.23252721, 0.23252721, 0.38754534, ..., 0.07750907, 0.07750907,
         0.15501814],
        [0.15344619, 0.15344619, 0.25574365, ..., 0.05114873, 0.05114873,
         0.10229746],
        ...,
        [0.15652963, 0.15652963, 0.26088271, ..., 0.05217654, 0.05217654,
         0.10435308],
        [0.42496977, 0.42496977, 0.70828295, ..., 0.14165659, 0.14165659,
         0.28331318],
        [0.12297461, 0.12297461, 0.20495768, ..., 0.04099154, 0.04099154,
         0.08198307]]))